#!/usr/bin/env python3
# Title: Vital City content-catalogue analysis
# Author: generated with Claude Code for Josh Greenman
# Date: 2026-07-02
# Data sources:
#   data/catalogue.json  — every published vitalcitynyc.org piece (Ghost Content
#                          API pull), 861 posts, 2021-09-15 -> 2026-07-02.
#   data/authors.json    — author roster with bios + post counts (Ghost authors).
#   Both regenerated by the catalogue pipeline; see data/meta.json for run stamp.
# Description: Aggregates the catalogue into the distributions charted on the
#   analysis page (by year, type, subject, author credential, length, etc.) and
#   writes data/catalogue_analysis.json. Pure recomputation from the two inputs.
# Dependencies: Python 3.9 stdlib only.
import json, re, collections, statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CAT = json.load(open(ROOT / "data/catalogue.json"))
AU  = json.load(open(ROOT / "data/authors.json"))
authors = {a["name"]: a for a in AU}

# ---------------------------------------------------------------------------
# Author credential classifier.
# Rule: bios are written "[Name] is a <primary role> and <secondary role>...", so
# the FIRST professional-identity keyword to appear in the bio wins ("is a
# reporter ... and teaches" -> Journalist, not Academic). Ties fall to GROUPS
# order. OVERRIDES fix the handful the heuristic misreads (verified by hand
# against the bio). This is an approximate, reproducible heuristic — not a
# hand-coded truth table — and single-label, though many authors hold several
# credentials at once (that overlap is discussed in the methodology note).
# ---------------------------------------------------------------------------
GROUPS = [
  ("Academic", r"\b(professor|lecturer|dean of|Ph\.?D\.? candidate|doctoral|postdoctoral|assistant professor|associate professor|faculty director|professor emerit|graduate student|research affiliate|research associate|adjunct)"),
  ("Government / public official", r"\b(commissioner|deputy mayor|\bmayor\b|governor|city council|councilmember|chief of police|police chief|district attorney|federal prosecutor|assistant U\.?S\.? attorney|public advocate|comptroller|borough president|White House|deputy director of the [A-Z]|former .{0,25}(commissioner|deputy mayor|chief|administrator))"),
  ("Legal practitioner", r"\b(attorney|lawyer|\bjudge\b|\bcounsel\b|law offices?|public defender|litigator)"),
  ("Journalist / media", r"\b(reporter|columnist|journalist|anchor|correspondent|editor of|op-ed editor|editorial page|managing editor|senior editor|contributing writer|contributing editor|staff writer|hosts?\b|co-host)"),
  ("Think tank / research institute", r"\b(senior fellow|research fellow|distinguished fellow|Manhattan Institute|Brookings|Urban Institute|RAND|NORC|director of research|research scientist|research director|vice president for research|policy analyst|Citizens Budget|budget commission)"),
  ("Nonprofit / advocacy", r"\b(executive director|nonprofit|non-profit|founder of the|president of the|advocate|advocacy|organizer|coalition|director of the [A-Z])"),
  ("Business / private sector", r"\b(venture capitalist|investor|entrepreneur|chief investment officer|\bCEO\b|philanthropist|partner at|planning firm|consultanc)"),
  ("Architecture / design / planning", r"\b(architect|urbanist|urban designer|urban planner|cartographer)"),
]
OVERRIDES = {
  "Greg Berman": "Nonprofit / advocacy",       # VC co-editor; nonprofit-leadership author
  "John Hall": "Government / public official",  # retired police professional
  "Ted Alcorn": "Journalist / media",           # NYT reporter who also teaches
  "Cara Eckholm": "Journalist / media",         # hosts VC interview series
  "Charles Komanoff": "Nonprofit / advocacy",   # congestion-pricing architect/advocate
  "Vishaan Chakrabarti": "Architecture / design / planning",
  "Michael Jacobson": "Academic",               # CUNY professor (also an institute director)
  "Julia D. Day": "Architecture / design / planning",  # team director at Gehl (urban design)
}
def classify(name):
    if not name: return "Unknown / no bio"
    if name.strip().lower() == "vital city": return "Vital City (institutional)"
    if name.strip().lower() in ("a survey", "survey"): return "Survey / reader poll"
    if name in OVERRIDES: return OVERRIDES[name]
    a = authors.get(name)
    bio = ((a.get("bio") if a else None) or "").strip()
    if not bio: return "Unknown / no bio"
    best = (10**9, None)
    for label, pat in GROUPS:
        m = re.search(pat, bio, re.I)
        if m and m.start() < best[0]:
            best = (m.start(), label)
    return best[1] or "Other / unclassified"

cred_of = {a["name"]: classify(a["name"]) for a in AU}

# ---------------------------------------------------------------------------
# Aggregations
# ---------------------------------------------------------------------------
def ymonth(d):  return (d or "")[:7]
def year(d):    return (d or "")[:4]

# 1. Over time
by_year = collections.Counter(year(a.get("published_date")) for a in CAT if a.get("published_date"))
by_month = collections.Counter(ymonth(a.get("published_date")) for a in CAT if a.get("published_date"))

# 2. Content type
by_type = collections.Counter(a.get("type") or "unknown" for a in CAT)

# 3. Subject matter (topics are multi-valued; a piece counts toward each topic)
by_topic = collections.Counter()
for a in CAT:
    for t in (a.get("topics") or []): by_topic[t] += 1

# 4. Author credential — by PRIMARY author of each piece (single byline unit)
by_cred = collections.Counter(cred_of.get(a.get("primary_author"), "Unknown / no bio") for a in CAT)
cred_author_count = collections.Counter(cred_of.values())  # distinct authors

# 5. Topic mix over time — top-8 topics by year (share of that year's pieces)
TOP_TOPICS = [t for t, _ in by_topic.most_common(8)]
topic_by_year = {t: collections.Counter() for t in TOP_TOPICS}
for a in CAT:
    y = year(a.get("published_date"))
    for t in (a.get("topics") or []):
        if t in topic_by_year: topic_by_year[t][y] += 1

# 6. Length
wc = sorted(a.get("word_count") or 0 for a in CAT if a.get("word_count"))
wc_buckets = collections.Counter()
for w in wc:
    b = ("<500" if w < 500 else "500-999" if w < 1000 else "1,000-1,999" if w < 2000
         else "2,000-2,999" if w < 3000 else "3,000-4,999" if w < 5000 else "5,000+")
    wc_buckets[b] += 1

# Fine 250-word bins for the actual shape of the distribution. The coarse
# buckets above put 59% of pieces in a single bar, which hides a tight peak
# and a long right tail. Everything at 3,500+ is collected in one final bin
# because the tail runs to 30,000 and would otherwise flatten the chart.
BIN, TAIL = 250, 3500
wc_hist = collections.Counter(min(w // BIN * BIN, TAIL) for w in wc)
wc_hist_rows = [{"floor": k, "label": (f"{TAIL:,}+" if k == TAIL else f"{k:,}"),
                 "n": wc_hist[k]} for k in sorted(wc_hist)]
def pct(p):
    return int(statistics.quantiles(wc, n=100)[p - 1])

# Length by year: has the house form drifted? Reported as an interquartile
# range with the median, not a mean — the tail would swamp a mean.
wc_year = {}
for a in CAT:
    w = a.get("word_count")
    if w:
        wc_year.setdefault(year(a.get("published_date")), []).append(w)
wc_by_year = []
for y in sorted(wc_year):
    v = sorted(wc_year[y])
    if len(v) < 10:      # 2021 is a single piece; not a distribution
        continue
    q = statistics.quantiles(v, n=4)
    wc_by_year.append({"year": y, "n": len(v), "p25": int(q[0]),
                       "median": int(statistics.median(v)), "p75": int(q[2]), "max": max(v)})

# 6b. Publishing cadence, with and without issue pieces.
# Issues do not arrive weekly — a whole issue lands on a single day (issue 16
# published all 23 of its pieces on 2026-06-10), so a raw pieces-per-week figure
# blends a steady stream with occasional 25-piece drops. Excluding issue pieces
# gives the cadence of the rolling operation.
#
# "In an issue" means carrying ANY internal (#) tag, numbered or named. The
# named ones are not standing series — they are issues named for their theme
# ("how-many-people-should-new-york-citys-jails-hold"), most publishing every
# piece on one day — so excluding only the numbered ones would overstate the
# standalone rate.
#
# Weeks are elapsed weeks, not 52: 2021 starts at launch and the current year
# stops at the pull date, so partial years are not understated.
import datetime
_meta = json.load(open(ROOT / "data/meta.json"))
LAUNCH = datetime.date(*map(int, _meta["date_range"][0].split("-")))
PULL   = datetime.date(*map(int, _meta["date_range"][1].split("-")))
def _weeks(y):
    start = max(datetime.date(int(y), 1, 1), LAUNCH)
    end   = min(datetime.date(int(y), 12, 31), PULL)
    return max((end - start).days / 7 + 1/7, 0.1)

cadence_by_year = []
for y in sorted({year(a.get("published_date")) for a in CAT if a.get("published_date")}):
    ps = [a for a in CAT if year(a.get("published_date")) == y]
    solo = [a for a in ps if not a.get("issues")]
    wks = _weeks(y)
    cadence_by_year.append({
      "year": y, "weeks": round(wks, 1), "pieces": len(ps), "outside_issues": len(solo),
      "per_week_all": round(len(ps)/wks, 2),
      "per_week_outside_issues": round(len(solo)/wks, 2),
      "partial": y in (LAUNCH.strftime("%Y"), PULL.strftime("%Y"))})
_tot_wks = sum(c["weeks"] for c in cadence_by_year)
_tot_solo = sum(c["outside_issues"] for c in cadence_by_year)
current = cadence_by_year[-1]
cadence = {
  "by_year": cadence_by_year,
  "total_weeks": round(_tot_wks, 1),
  "all_time_per_week": round(len(CAT)/_tot_wks, 2),
  "all_time_per_week_outside_issues": round(_tot_solo/_tot_wks, 2),
  "current_year": current["year"],
  "current_per_week_outside_issues": current["per_week_outside_issues"],
  "current_per_week_all": current["per_week_all"],
}

# 6c. Publishing rhythm — which day of the week, which month.
# The cadence figures above are averages; this is what the average is made of.
# Weekday is derived from the publication date, so it reflects when a piece went
# live, not when it was written or edited.
WD = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
MONTHS = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]
_wd, _mo = collections.Counter(), collections.Counter()
for a in CAT:
    ds = a.get("published_date")
    if not ds:
        continue
    dt = datetime.date(*map(int, ds.split("-")))
    _wd[WD[dt.weekday()]] += 1
    _mo[dt.month] += 1
_dated = sum(_wd.values())
# Months are normalised per occurrence of that month in the covered period, so a
# month the catalogue has lived through five times is not flattered over one it
# has seen four times.
_month_spans = collections.Counter()
_m, _y0 = LAUNCH.month, LAUNCH.year
while (_y0, _m) <= (PULL.year, PULL.month):
    _month_spans[_m] += 1
    _m = 1 if _m == 12 else _m + 1
    if _m == 1:
        _y0 += 1
rhythm = {
  "n_dated": _dated,
  "by_weekday": [{"day": d, "pieces": _wd[d], "share": round(_wd[d]/_dated*100, 1)} for d in WD],
  "top_day": max(WD, key=lambda d: _wd[d]),
  "top_day_share": round(max(_wd.values())/_dated*100, 1),
  "midweek_share": round(sum(_wd[d] for d in ("Tue", "Wed", "Thu"))/_dated*100, 1),
  "weekend_pieces": _wd["Sat"] + _wd["Sun"],
  "by_month": [{"month": MONTHS[m-1], "abbr": MONTHS[m-1][:3], "pieces": _mo[m],
                "occurrences": _month_spans[m],
                "per_occurrence": round(_mo[m]/_month_spans[m], 1)} for m in range(1, 13)],
}

# 7. Collaboration
by_nauthors = collections.Counter(len(a.get("authors") or []) for a in CAT)

# 8. Most prolific authors (with credential)
prolific = [{"name": a["name"], "posts": a.get("post_count") or 0,
             "credential": cred_of.get(a["name"], "Unknown / no bio")}
            for a in sorted(AU, key=lambda a: -(a.get("post_count") or 0))[:20]]

# 9. Issues (themed collections)
issues = json.load(open(ROOT / "data/issues.json"))

out = {
  "meta": json.load(open(ROOT / "data/meta.json")),
  "total_pieces": len(CAT),
  "by_year": dict(sorted(by_year.items())),
  "by_month": dict(sorted(by_month.items())),
  "by_type": by_type.most_common(),
  "by_topic_top25": by_topic.most_common(25),
  "n_topics_total": len(by_topic),
  "by_credential_pieces": by_cred.most_common(),
  "by_credential_authors": cred_author_count.most_common(),
  "top_topics_for_stack": TOP_TOPICS,
  "topic_by_year": {t: dict(sorted(c.items())) for t, c in topic_by_year.items()},
  "wc_stats": {"n": len(wc), "median": int(statistics.median(wc)),
               "mean": round(statistics.mean(wc)), "p90": wc[int(.9*len(wc))-1], "max": max(wc),
               "p10": pct(10), "p25": pct(25), "p75": pct(75), "p95": pct(95),
               "no_count": len(CAT) - len(wc),
               "core_1000_2499": sum(1 for w in wc if 1000 <= w < 2500),
               "under_500": sum(1 for w in wc if w < 500),
               "over_5000": sum(1 for w in wc if w >= 5000)},
  "wc_buckets": [(k, wc_buckets[k]) for k in ["<500","500-999","1,000-1,999","2,000-2,999","3,000-4,999","5,000+"]],
  "wc_hist": {"bin": BIN, "tail_floor": TAIL, "rows": wc_hist_rows},
  "wc_by_year": wc_by_year,
  "by_nauthors": dict(sorted(by_nauthors.items())),
  "prolific": prolific,
  "n_issues": len(issues),
  "cadence": cadence,
  "rhythm": rhythm,
}
(ROOT / "data/catalogue_analysis.json").write_text(json.dumps(out, indent=2))

# ---- validation output ----
print("wrote data/catalogue_analysis.json")
print("\nCredential mix by PIECES (primary author):")
for k, v in out["by_credential_pieces"]:
    print(f"  {v:>4} ({v/len(CAT)*100:4.1f}%)  {k}")
print("\nUnknown/Other authors among top 60 by post_count (spot-check):")
for a in sorted(AU, key=lambda a: -(a.get("post_count") or 0))[:60]:
    c = cred_of[a["name"]]
    if c in ("Unknown / no bio", "Other / unclassified"):
        print(f"  [{a.get('post_count')}] {a['name']}: {(a.get('bio') or '')[:80]}")
