#!/usr/bin/env python3
# Title: Vital City content-catalogue analysis
# Author: generated with Claude Code for Josh Greenman
# Date: 2026-07-02
# Data sources:
#   data/catalogue.json  — every published vitalcitynyc.org piece (Ghost Content
#                          API pull), 861 posts, 2021-09-15 -> 2026-07-02.
#   data/authors.json    — author roster with bios + post counts (Ghost authors).
#   Both regenerated by the catalogue pipeline; see data/meta.json for run stamp.
# Description: Aggregates the catalogue into the distributions charted on the
#   analysis page (by year, type, subject, author credential, length, etc.) and
#   writes data/catalogue_analysis.json. Pure recomputation from the two inputs.
# Dependencies: Python 3.9 stdlib only.
import json, re, collections, statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CAT = json.load(open(ROOT / "data/catalogue.json"))
AU  = json.load(open(ROOT / "data/authors.json"))
authors = {a["name"]: a for a in AU}

# ---------------------------------------------------------------------------
# Author credential classifier.
# Rule: bios are written "[Name] is a <primary role> and <secondary role>...", so
# the FIRST professional-identity keyword to appear in the bio wins ("is a
# reporter ... and teaches" -> Journalist, not Academic). Ties fall to GROUPS
# order. OVERRIDES fix the handful the heuristic misreads (verified by hand
# against the bio). This is an approximate, reproducible heuristic — not a
# hand-coded truth table — and single-label, though many authors hold several
# credentials at once (that overlap is discussed in the methodology note).
# ---------------------------------------------------------------------------
GROUPS = [
  ("Academic", r"\b(professor|lecturer|dean of|Ph\.?D\.? candidate|doctoral|postdoctoral|assistant professor|associate professor|faculty director|professor emerit|graduate student|research affiliate|research associate|adjunct)"),
  ("Government / public official", r"\b(commissioner|deputy mayor|\bmayor\b|governor|city council|councilmember|chief of police|police chief|district attorney|federal prosecutor|assistant U\.?S\.? attorney|public advocate|comptroller|borough president|White House|deputy director of the [A-Z]|former .{0,25}(commissioner|deputy mayor|chief|administrator))"),
  ("Legal practitioner", r"\b(attorney|lawyer|\bjudge\b|\bcounsel\b|law offices?|public defender|litigator)"),
  ("Journalist / media", r"\b(reporter|columnist|journalist|anchor|correspondent|editor of|op-ed editor|editorial page|managing editor|senior editor|contributing writer|contributing editor|staff writer|hosts?\b|co-host)"),
  ("Think tank / research institute", r"\b(senior fellow|research fellow|distinguished fellow|Manhattan Institute|Brookings|Urban Institute|RAND|NORC|director of research|research scientist|research director|vice president for research|policy analyst|Citizens Budget|budget commission)"),
  ("Nonprofit / advocacy", r"\b(executive director|nonprofit|non-profit|founder of the|president of the|advocate|advocacy|organizer|coalition|director of the [A-Z])"),
  ("Business / private sector", r"\b(venture capitalist|investor|entrepreneur|chief investment officer|\bCEO\b|philanthropist|partner at|planning firm|consultanc)"),
  ("Architecture / design / planning", r"\b(architect|urbanist|urban designer|urban planner|cartographer)"),
]
OVERRIDES = {
  "Greg Berman": "Nonprofit / advocacy",       # VC co-editor; nonprofit-leadership author
  "John Hall": "Government / public official",  # retired police professional
  "Ted Alcorn": "Journalist / media",           # NYT reporter who also teaches
  "Cara Eckholm": "Journalist / media",         # hosts VC interview series
  "Charles Komanoff": "Nonprofit / advocacy",   # congestion-pricing architect/advocate
  "Vishaan Chakrabarti": "Architecture / design / planning",
  "Michael Jacobson": "Academic",               # CUNY professor (also an institute director)
  "Julia D. Day": "Architecture / design / planning",  # team director at Gehl (urban design)
}
def classify(name):
    if not name: return "Unknown / no bio"
    if name.strip().lower() == "vital city": return "Vital City (institutional)"
    if name.strip().lower() in ("a survey", "survey"): return "Survey / reader poll"
    if name in OVERRIDES: return OVERRIDES[name]
    a = authors.get(name)
    bio = ((a.get("bio") if a else None) or "").strip()
    if not bio: return "Unknown / no bio"
    best = (10**9, None)
    for label, pat in GROUPS:
        m = re.search(pat, bio, re.I)
        if m and m.start() < best[0]:
            best = (m.start(), label)
    return best[1] or "Other / unclassified"

cred_of = {a["name"]: classify(a["name"]) for a in AU}

# ---------------------------------------------------------------------------
# Aggregations
# ---------------------------------------------------------------------------
def ymonth(d):  return (d or "")[:7]
def year(d):    return (d or "")[:4]

# 1. Over time
by_year = collections.Counter(year(a.get("published_date")) for a in CAT if a.get("published_date"))
by_month = collections.Counter(ymonth(a.get("published_date")) for a in CAT if a.get("published_date"))

# 2. Content type
by_type = collections.Counter(a.get("type") or "unknown" for a in CAT)

# 3. Subject matter (topics are multi-valued; a piece counts toward each topic)
by_topic = collections.Counter()
for a in CAT:
    for t in (a.get("topics") or []): by_topic[t] += 1

# 4. Author credential — by PRIMARY author of each piece (single byline unit)
by_cred = collections.Counter(cred_of.get(a.get("primary_author"), "Unknown / no bio") for a in CAT)
cred_author_count = collections.Counter(cred_of.values())  # distinct authors

# 5. Topic mix over time — top-8 topics by year (share of that year's pieces)
TOP_TOPICS = [t for t, _ in by_topic.most_common(8)]
topic_by_year = {t: collections.Counter() for t in TOP_TOPICS}
for a in CAT:
    y = year(a.get("published_date"))
    for t in (a.get("topics") or []):
        if t in topic_by_year: topic_by_year[t][y] += 1

# 6. Length
wc = sorted(a.get("word_count") or 0 for a in CAT if a.get("word_count"))
wc_buckets = collections.Counter()
for w in wc:
    b = ("<500" if w < 500 else "500-999" if w < 1000 else "1,000-1,999" if w < 2000
         else "2,000-2,999" if w < 3000 else "3,000-4,999" if w < 5000 else "5,000+")
    wc_buckets[b] += 1

# 7. Collaboration
by_nauthors = collections.Counter(len(a.get("authors") or []) for a in CAT)

# 8. Most prolific authors (with credential)
prolific = [{"name": a["name"], "posts": a.get("post_count") or 0,
             "credential": cred_of.get(a["name"], "Unknown / no bio")}
            for a in sorted(AU, key=lambda a: -(a.get("post_count") or 0))[:20]]

# 9. Issues (themed collections)
issues = json.load(open(ROOT / "data/issues.json"))

out = {
  "meta": json.load(open(ROOT / "data/meta.json")),
  "total_pieces": len(CAT),
  "by_year": dict(sorted(by_year.items())),
  "by_month": dict(sorted(by_month.items())),
  "by_type": by_type.most_common(),
  "by_topic_top25": by_topic.most_common(25),
  "n_topics_total": len(by_topic),
  "by_credential_pieces": by_cred.most_common(),
  "by_credential_authors": cred_author_count.most_common(),
  "top_topics_for_stack": TOP_TOPICS,
  "topic_by_year": {t: dict(sorted(c.items())) for t, c in topic_by_year.items()},
  "wc_stats": {"n": len(wc), "median": int(statistics.median(wc)),
               "mean": round(statistics.mean(wc)), "p90": wc[int(.9*len(wc))-1], "max": max(wc)},
  "wc_buckets": [(k, wc_buckets[k]) for k in ["<500","500-999","1,000-1,999","2,000-2,999","3,000-4,999","5,000+"]],
  "by_nauthors": dict(sorted(by_nauthors.items())),
  "prolific": prolific,
  "n_issues": len(issues),
}
(ROOT / "data/catalogue_analysis.json").write_text(json.dumps(out, indent=2))

# ---- validation output ----
print("wrote data/catalogue_analysis.json")
print("\nCredential mix by PIECES (primary author):")
for k, v in out["by_credential_pieces"]:
    print(f"  {v:>4} ({v/len(CAT)*100:4.1f}%)  {k}")
print("\nUnknown/Other authors among top 60 by post_count (spot-check):")
for a in sorted(AU, key=lambda a: -(a.get("post_count") or 0))[:60]:
    c = cred_of[a["name"]]
    if c in ("Unknown / no bio", "Other / unclassified"):
        print(f"  [{a.get('post_count')}] {a['name']}: {(a.get('bio') or '')[:80]}")
